"""
PPS Anantam — Universal Share System v1.0
============================================
Centralized sharing to WhatsApp + Telegram + Email + PDF.
Formats messages per channel, sends via engine, logs to share_history.json.
"""
import json
import uuid
from pathlib import Path
from datetime import datetime, timezone, timedelta

# ═══════════════════════════════════════════════════════════════════════════════
# Constants
# ═══════════════════════════════════════════════════════════════════════════════

IST = timezone(timedelta(hours=5, minutes=30))
_BASE = Path(__file__).parent
_HISTORY_FILE = _BASE / "share_history.json"
_SCHEDULES_FILE = _BASE / "share_schedules.json"

_MAX_HISTORY = 500

_COMPANY_NAME = "PPS Anantam Agentic AI Eco System"
_CONFIDENTIAL_FOOTER = (
    "CONFIDENTIAL — This communication is intended solely for the named "
    "recipient(s). If you have received this in error, please notify the "
    "sender immediately and delete all copies."
)


# ═══════════════════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════════════════

def _now_ist() -> str:
    """Return current IST timestamp as ISO-8601 string."""
    return datetime.now(IST).strftime("%Y-%m-%d %H:%M:%S")


def _now_ist_dt() -> datetime:
    """Return current IST datetime object."""
    return datetime.now(IST)


def _date_display() -> str:
    """Human-readable date for messages, e.g. '23-Mar-2026'."""
    return datetime.now(IST).strftime("%d-%b-%Y")


def _time_display() -> str:
    """Human-readable time, e.g. '14:35'."""
    return datetime.now(IST).strftime("%H:%M")


def _gen_id() -> str:
    """Short unique ID for log entries."""
    return uuid.uuid4().hex[:12]


# ═══════════════════════════════════════════════════════════════════════════════
# Message Formatting
# ═══════════════════════════════════════════════════════════════════════════════

def _format_data_lines(data: dict) -> list[str]:
    """
    Extract 5-8 concise data lines from a data dict.

    Supported keys in *data*:
        summary    : str       — single-line summary
        kpis       : list[dict]— each has 'label', 'value', optional 'delta'
        table_data : list      — list of dicts or lists (first few rows)
        chart_url  : str       — link to an online chart image
    """
    lines: list[str] = []
    if not data:
        return lines

    # Summary
    summary = data.get("summary")
    if summary:
        lines.append(summary)

    # KPIs
    kpis = data.get("kpis") or []
    for kpi in kpis[:6]:
        label = kpi.get("label", "")
        value = kpi.get("value", "")
        delta = kpi.get("delta", "")
        if delta:
            lines.append(f"  {label}: {value}  ({delta})")
        else:
            lines.append(f"  {label}: {value}")

    # Table (first 3 rows, compact)
    table_data = data.get("table_data") or []
    for row in table_data[:3]:
        if isinstance(row, dict):
            parts = [f"{k}: {v}" for k, v in row.items()]
            lines.append("  " + " | ".join(parts))
        elif isinstance(row, (list, tuple)):
            lines.append("  " + " | ".join(str(c) for c in row))

    # Chart link
    chart_url = data.get("chart_url")
    if chart_url:
        lines.append(f"  Chart: {chart_url}")

    return lines[:8]  # cap at 8 lines


def format_message(
    page_name: str,
    data: dict = None,
    channel: str = "whatsapp",
) -> str:
    """
    Format share message for a given channel.

    WhatsApp / Telegram (compact):
        Emoji header, date/time IST, key data points, footer.

    Email (detailed):
        HTML body with company header, tabular data, confidential footer.
    """
    date_str = _date_display()
    time_str = _time_display()
    data_lines = _format_data_lines(data)

    # ── WhatsApp / Telegram (plain-text, compact) ────────────────────────
    if channel in ("whatsapp", "telegram"):
        body_lines = data_lines if data_lines else ["No additional data."]
        msg = (
            f"\U0001f3db\ufe0f PPS ANANTAM \u2014 {page_name}\n"
            f"{date_str}, {time_str} IST\n"
            f"\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\n"
            + "\n".join(body_lines) + "\n"
            f"\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\n"
            f"Generated by PPS Bitumen Dashboard"
        )
        return msg

    # ── Email (HTML) ─────────────────────────────────────────────────────
    if channel == "email":
        # Build KPI rows for HTML table
        kpi_html = ""
        kpis = (data or {}).get("kpis") or []
        if kpis:
            kpi_rows = ""
            for kpi in kpis:
                label = kpi.get("label", "")
                value = kpi.get("value", "")
                delta = kpi.get("delta", "")
                delta_span = (
                    f' <span style="color:#4CAF50;font-size:12px;">({delta})</span>'
                    if delta else ""
                )
                kpi_rows += (
                    f"<tr>"
                    f"<td style='padding:6px 12px;border:1px solid #ddd;'>{label}</td>"
                    f"<td style='padding:6px 12px;border:1px solid #ddd;"
                    f"font-weight:bold;'>{value}{delta_span}</td>"
                    f"</tr>\n"
                )
            kpi_html = (
                "<table style='border-collapse:collapse;width:100%;margin:12px 0;'>"
                "<thead><tr>"
                "<th style='padding:8px 12px;background:#1B2A4A;color:#fff;"
                "border:1px solid #1B2A4A;text-align:left;'>Metric</th>"
                "<th style='padding:8px 12px;background:#1B2A4A;color:#fff;"
                "border:1px solid #1B2A4A;text-align:left;'>Value</th>"
                "</tr></thead><tbody>\n"
                + kpi_rows +
                "</tbody></table>"
            )

        # Build table data rows
        table_html = ""
        table_data = (data or {}).get("table_data") or []
        if table_data:
            # Determine headers
            if table_data and isinstance(table_data[0], dict):
                headers = list(table_data[0].keys())
                trows = ""
                for row in table_data[:20]:
                    cells = "".join(
                        f"<td style='padding:6px 12px;border:1px solid #ddd;'>"
                        f"{row.get(h, '')}</td>"
                        for h in headers
                    )
                    trows += f"<tr>{cells}</tr>\n"
                thead = "".join(
                    f"<th style='padding:8px 12px;background:#1B2A4A;color:#fff;"
                    f"border:1px solid #1B2A4A;text-align:left;'>{h}</th>"
                    for h in headers
                )
            elif table_data and isinstance(table_data[0], (list, tuple)):
                thead = "".join(
                    f"<th style='padding:8px 12px;background:#1B2A4A;color:#fff;"
                    f"border:1px solid #1B2A4A;text-align:left;'>Col {i+1}</th>"
                    for i in range(len(table_data[0]))
                )
                trows = ""
                for row in table_data[:20]:
                    cells = "".join(
                        f"<td style='padding:6px 12px;border:1px solid #ddd;'>"
                        f"{c}</td>"
                        for c in row
                    )
                    trows += f"<tr>{cells}</tr>\n"
            else:
                thead = ""
                trows = ""

            if thead:
                table_html = (
                    "<table style='border-collapse:collapse;width:100%;"
                    "margin:12px 0;'>"
                    f"<thead><tr>{thead}</tr></thead>"
                    f"<tbody>{trows}</tbody></table>"
                )

        summary_text = (data or {}).get("summary", "")
        summary_html = (
            f"<p style='font-size:14px;color:#333;'>{summary_text}</p>"
            if summary_text else ""
        )

        chart_url = (data or {}).get("chart_url", "")
        chart_html = (
            f"<p><img src='{chart_url}' alt='Chart' "
            f"style='max-width:100%;border:1px solid #ddd;'/></p>"
            if chart_url else ""
        )

        html = f"""\
<div style="font-family:Segoe UI,Arial,sans-serif;max-width:700px;margin:auto;">
  <!-- Header -->
  <div style="background:#1B2A4A;padding:18px 24px;border-radius:8px 8px 0 0;">
    <h1 style="margin:0;color:#D4AF37;font-size:22px;">
      \U0001f3db\ufe0f {_COMPANY_NAME}
    </h1>
    <p style="margin:4px 0 0;color:#ccc;font-size:13px;">
      {page_name} &nbsp;|&nbsp; {date_str} &nbsp;|&nbsp; {time_str} IST
    </p>
  </div>

  <!-- Body -->
  <div style="padding:20px 24px;background:#fff;border:1px solid #e0e0e0;">
    {summary_html}
    {kpi_html}
    {table_html}
    {chart_html}
  </div>

  <!-- Footer -->
  <div style="background:#f5f5f5;padding:14px 24px;border-radius:0 0 8px 8px;
              border:1px solid #e0e0e0;border-top:none;font-size:11px;color:#888;">
    <p style="margin:0 0 6px;">
      Generated by <strong>PPS Bitumen Dashboard</strong>
    </p>
    <p style="margin:0;font-style:italic;">
      {_CONFIDENTIAL_FOOTER}
    </p>
  </div>
</div>"""
        return html

    # ── Fallback: treat like WhatsApp ────────────────────────────────────
    return format_message(page_name, data, channel="whatsapp")


# ═══════════════════════════════════════════════════════════════════════════════
# Logging
# ═══════════════════════════════════════════════════════════════════════════════

def _log_share(
    channel: str,
    page_name: str,
    recipient: str,
    status: str,
    error: str = "",
) -> None:
    """
    Log a share action to share_history.json.
    Keeps the most recent *_MAX_HISTORY* entries.
    """
    entry = {
        "id": _gen_id(),
        "timestamp": _now_ist(),
        "channel": channel,
        "page_name": page_name,
        "recipient": recipient,
        "status": status,
        "error": error,
    }
    try:
        history: list = []
        if _HISTORY_FILE.exists():
            raw = _HISTORY_FILE.read_text(encoding="utf-8").strip()
            if raw:
                history = json.loads(raw)
        history.append(entry)
        # Keep only the latest _MAX_HISTORY entries
        history = history[-_MAX_HISTORY:]
        _HISTORY_FILE.write_text(
            json.dumps(history, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
    except Exception:
        pass  # logging must never crash the caller


def get_share_history(limit: int = 50) -> list:
    """Return the most recent *limit* share-history entries (newest first)."""
    try:
        if not _HISTORY_FILE.exists():
            return []
        raw = _HISTORY_FILE.read_text(encoding="utf-8").strip()
        if not raw:
            return []
        history = json.loads(raw)
        return list(reversed(history[-limit:]))
    except Exception:
        return []


# ═══════════════════════════════════════════════════════════════════════════════
# WhatsApp
# ═══════════════════════════════════════════════════════════════════════════════

def share_whatsapp(
    phone: str,
    page_name: str,
    data: dict = None,
) -> dict:
    """
    Send a message via the WhatsApp queue.

    Inserts into the *whatsapp_queue* table (database.py) with
    status='queued'.  If the database layer is unavailable, falls back to
    returning the formatted message text so the caller can still use it
    (e.g. copy-paste into WhatsApp Web).

    Returns ``{success: bool, message_id: str|None, error: str}``.
    """
    formatted = format_message(page_name, data, channel="whatsapp")
    result = {"success": False, "message_id": None, "error": ""}

    try:
        from database import insert_wa_queue, _now_ist as db_now  # noqa: F811

        queue_id = insert_wa_queue({
            "to_number": phone,
            "message_type": "share",
            "session_text": formatted,
            "status": "queued",
            "scheduled_at": db_now(),
        })
        result["success"] = True
        result["message_id"] = f"wa-{queue_id}"
        _log_share("whatsapp", page_name, phone, "queued")

    except ImportError:
        # Database module not available — return message as fallback
        result["success"] = True
        result["message_id"] = f"wa-local-{_gen_id()}"
        result["formatted_text"] = formatted
        _log_share("whatsapp", page_name, phone, "fallback",
                   "database module not available — message text returned")

    except Exception as exc:
        result["error"] = str(exc)
        _log_share("whatsapp", page_name, phone, "error", str(exc))

    return result


# ═══════════════════════════════════════════════════════════════════════════════
# Telegram
# ═══════════════════════════════════════════════════════════════════════════════

def share_telegram(
    chat_id: str,
    page_name: str,
    data: dict = None,
) -> dict:
    """
    Send a message via the Telegram engine.

    Imports ``send_message`` from ``telegram_engine`` and posts with
    ``parse_mode="HTML"``.

    Returns ``{success: bool, message_id: str|None, error: str}``.
    """
    formatted = format_message(page_name, data, channel="telegram")
    result = {"success": False, "message_id": None, "error": ""}

    try:
        from telegram_engine import send_message as tg_send  # type: ignore

        resp = tg_send(chat_id, formatted, parse_mode="HTML")
        # tg_send may return a dict with message_id or a raw response
        if isinstance(resp, dict):
            msg_id = resp.get("message_id") or resp.get("result", {}).get("message_id")
        else:
            msg_id = str(resp) if resp else None

        result["success"] = True
        result["message_id"] = f"tg-{msg_id}" if msg_id else f"tg-{_gen_id()}"
        _log_share("telegram", page_name, chat_id, "sent")

    except ImportError:
        # Telegram engine not available — return formatted text as fallback
        result["success"] = True
        result["message_id"] = f"tg-local-{_gen_id()}"
        result["formatted_text"] = formatted
        _log_share("telegram", page_name, chat_id, "fallback",
                   "telegram_engine module not available — message text returned")

    except Exception as exc:
        result["error"] = str(exc)
        _log_share("telegram", page_name, chat_id, "error", str(exc))

    return result


# ═══════════════════════════════════════════════════════════════════════════════
# Email
# ═══════════════════════════════════════════════════════════════════════════════

def share_email(
    to_email: str,
    page_name: str,
    data: dict = None,
    subject: str = None,
) -> dict:
    """
    Queue an email via the database email_queue table.

    Returns ``{success: bool, message_id: str|None, error: str}``.
    """
    date_str = _date_display()
    subject = subject or f"PPS Anantam \u2014 {page_name} | {date_str}"
    body_html = format_message(page_name, data, channel="email")
    result = {"success": False, "message_id": None, "error": ""}

    try:
        from database import insert_email_queue, _now_ist as db_now  # noqa: F811

        queue_id = insert_email_queue({
            "to_email": to_email,
            "subject": subject,
            "body_html": body_html,
            "email_type": "share",
            "status": "queued",
            "scheduled_at": db_now(),
        })
        result["success"] = True
        result["message_id"] = f"email-{queue_id}"
        _log_share("email", page_name, to_email, "queued")

    except ImportError:
        # Database not available — return the HTML body so caller can still use it
        result["success"] = True
        result["message_id"] = f"email-local-{_gen_id()}"
        result["formatted_html"] = body_html
        result["subject"] = subject
        _log_share("email", page_name, to_email, "fallback",
                   "database module not available — HTML body returned")

    except Exception as exc:
        result["error"] = str(exc)
        _log_share("email", page_name, to_email, "error", str(exc))

    return result


# ═══════════════════════════════════════════════════════════════════════════════
# PDF
# ═══════════════════════════════════════════════════════════════════════════════

def share_pdf(
    page_name: str,
    data: dict = None,
) -> bytes | None:
    """
    Generate PDF bytes for the given page data using PDFExportEngine.

    Returns raw PDF bytes, or *None* if PDF generation is unavailable.
    """
    try:
        from pdf_export_engine import PDFExportEngine  # type: ignore

        engine = PDFExportEngine(page_name)

        # Title
        engine.add_title(page_name)

        # Summary paragraph
        summary = (data or {}).get("summary", "")
        if summary:
            engine.add_section("Summary")
            engine.add_paragraph(summary)

        # KPIs
        kpis = (data or {}).get("kpis") or []
        if kpis:
            engine.add_section("Key Metrics")
            kpi_tuples = []
            for kpi in kpis:
                label = kpi.get("label", "")
                value = kpi.get("value", "")
                delta = kpi.get("delta", "")
                kpi_tuples.append((label, str(value), str(delta)))
            engine.add_kpi_row(kpi_tuples)

        # Table data
        table_data = (data or {}).get("table_data") or []
        if table_data:
            engine.add_section("Data")
            if isinstance(table_data[0], dict):
                headers = list(table_data[0].keys())
                rows = [[row.get(h, "") for h in headers] for row in table_data]
            elif isinstance(table_data[0], (list, tuple)):
                headers = [f"Col {i+1}" for i in range(len(table_data[0]))]
                rows = [list(r) for r in table_data]
            else:
                headers = ["Value"]
                rows = [[str(v)] for v in table_data]
            engine.add_table(headers, rows)

        pdf_bytes = engine.build(save_to_archive=False)
        _log_share("pdf", page_name, "local", "generated")
        return pdf_bytes

    except ImportError:
        _log_share("pdf", page_name, "local", "fallback",
                   "pdf_export_engine module not available")
        return None

    except Exception as exc:
        _log_share("pdf", page_name, "local", "error", str(exc))
        return None


# ═══════════════════════════════════════════════════════════════════════════════
# Broadcast / Share-to-All
# ═══════════════════════════════════════════════════════════════════════════════

def share_to_all(
    page_name: str,
    data: dict = None,
    channels: list = None,
) -> list:
    """
    Send to multiple channels in one call.

    *channels* is a list of dicts, each with:
        ``{"type": "whatsapp"|"telegram"|"email", "recipient": "..."}``

    If *channels* is ``None`` or empty, returns an empty list.
    Returns a list of per-channel result dicts.
    """
    if not channels:
        return []

    results = []
    for ch in channels:
        ch_type = ch.get("type", "").lower()
        recipient = ch.get("recipient", "")

        try:
            if ch_type == "whatsapp":
                res = share_whatsapp(recipient, page_name, data)
            elif ch_type == "telegram":
                res = share_telegram(recipient, page_name, data)
            elif ch_type == "email":
                res = share_email(recipient, page_name, data)
            elif ch_type == "pdf":
                pdf_bytes = share_pdf(page_name, data)
                res = {
                    "success": pdf_bytes is not None,
                    "message_id": f"pdf-{_gen_id()}" if pdf_bytes else None,
                    "error": "" if pdf_bytes else "PDF generation failed",
                    "pdf_bytes": pdf_bytes,
                }
            else:
                res = {
                    "success": False,
                    "message_id": None,
                    "error": f"Unknown channel type: {ch_type}",
                }
        except Exception as exc:
            res = {
                "success": False,
                "message_id": None,
                "error": str(exc),
            }

        res["channel"] = ch_type
        res["recipient"] = recipient
        results.append(res)

    return results


# ═══════════════════════════════════════════════════════════════════════════════
# Scheduled Sharing
# ═══════════════════════════════════════════════════════════════════════════════

def schedule_share(
    page_name: str,
    data_fn: str,
    channel: str,
    schedule_time: str,
    recipients: list,
) -> dict:
    """
    Schedule a share for future execution.

    Saves to ``share_schedules.json``.  A separate scheduler process
    (or a Streamlit background thread) should poll this file and fire
    the shares at the appropriate time.

    Parameters
    ----------
    page_name : str
        Dashboard page to share.
    data_fn : str
        Fully-qualified function name that returns the data dict at
        execution time (e.g. ``"pages.dashboard.get_summary_data"``).
    channel : str
        ``"whatsapp"`` | ``"telegram"`` | ``"email"``.
    schedule_time : str
        ISO-8601 datetime string in IST (e.g. ``"2026-03-24 09:00:00"``).
    recipients : list[str]
        Phone numbers, chat IDs, or email addresses.

    Returns
    -------
    dict
        ``{success, schedule_id, error}``
    """
    schedule_id = _gen_id()
    entry = {
        "id": schedule_id,
        "page_name": page_name,
        "data_fn": data_fn,
        "channel": channel,
        "schedule_time": schedule_time,
        "recipients": recipients,
        "status": "scheduled",
        "created_at": _now_ist(),
    }

    try:
        schedules: list = []
        if _SCHEDULES_FILE.exists():
            raw = _SCHEDULES_FILE.read_text(encoding="utf-8").strip()
            if raw:
                schedules = json.loads(raw)

        schedules.append(entry)
        _SCHEDULES_FILE.write_text(
            json.dumps(schedules, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        _log_share(channel, page_name, ", ".join(recipients), "scheduled")
        return {"success": True, "schedule_id": schedule_id, "error": ""}

    except Exception as exc:
        _log_share(channel, page_name, ", ".join(recipients), "schedule_error",
                   str(exc))
        return {"success": False, "schedule_id": None, "error": str(exc)}


# ═══════════════════════════════════════════════════════════════════════════════
# Module self-test
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    sample_data = {
        "summary": "Monthly bitumen sales up 12% vs last month.",
        "kpis": [
            {"label": "Total Sales", "value": "4,250 MT", "delta": "+12%"},
            {"label": "Revenue", "value": "\u20b918.7 Cr", "delta": "+8.5%"},
            {"label": "Active Customers", "value": "142", "delta": "+5"},
        ],
        "table_data": [
            {"Region": "North", "Volume": "1,200 MT", "Revenue": "\u20b95.2 Cr"},
            {"Region": "West", "Volume": "1,050 MT", "Revenue": "\u20b94.6 Cr"},
            {"Region": "South", "Volume": "1,000 MT", "Revenue": "\u20b94.4 Cr"},
            {"Region": "East", "Volume": "1,000 MT", "Revenue": "\u20b94.5 Cr"},
        ],
    }

    print("=" * 60)
    print("WhatsApp format:")
    print("=" * 60)
    print(format_message("Sales Dashboard", sample_data, "whatsapp"))

    print("\n" + "=" * 60)
    print("Email format (HTML):")
    print("=" * 60)
    print(format_message("Sales Dashboard", sample_data, "email")[:500], "...")

    print("\n" + "=" * 60)
    print("share_whatsapp (fallback mode):")
    print("=" * 60)
    res = share_whatsapp("+919876543210", "Sales Dashboard", sample_data)
    print(json.dumps({k: v for k, v in res.items()
                      if k != "formatted_text"}, indent=2))

    print("\n" + "=" * 60)
    print("Share history:")
    print("=" * 60)
    history = get_share_history(5)
    print(json.dumps(history, indent=2))
