"""
PPS Bitumen Dashboard v5.0 — Share Button Component
Clean White Theme | Reusable share dropdown with multi-channel support.
"""

import streamlit as st
from datetime import datetime, date, time as dt_time

# ── Theme Colors ──────────────────────────────────────────────
BLUE_PRIMARY = "#2563eb"
BLUE_HOVER   = "#1d4ed8"
BLUE_LIGHT   = "#dbeafe"
GREEN        = "#059669"
RED          = "#dc2626"
AMBER        = "#f59e0b"
SLATE_50     = "#f8fafc"
SLATE_200    = "#e2e8f0"
SLATE_500    = "#64748b"
SLATE_700    = "#334155"
SLATE_900    = "#0f172a"
WHITE        = "#ffffff"


def _build_share_message(page_name: str, summary: str = None) -> str:
    """Build the formatted share message string."""
    now = datetime.now()
    date_str = now.strftime("%d %b %Y")
    time_str = now.strftime("%I:%M %p")
    body = summary if summary else "View details in PPS Dashboard"

    msg = (
        f"\U0001f3db\ufe0f PPS ANANTAM \u2014 {page_name}\n"
        f"{date_str}, {time_str} IST\n"
        f"\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\n"
        f"{body}\n"
        f"\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\n"
        f"Generated by PPS Bitumen Dashboard"
    )
    return msg


def _get_summary_from_data(data_fn) -> str:
    """Extract summary text from the data function if available."""
    if data_fn is None:
        return None
    try:
        data = data_fn()
        if isinstance(data, dict) and "summary" in data:
            return data["summary"]
    except Exception:
        pass
    return None


def _get_dataframe_from_data(data_fn):
    """Extract DataFrame from the data function if available."""
    if data_fn is None:
        return None
    try:
        data = data_fn()
        if isinstance(data, dict) and "table" in data:
            return data["table"]
    except Exception:
        pass
    return None


def _get_chart_from_data(data_fn):
    """Extract chart figure from the data function if available."""
    if data_fn is None:
        return None
    try:
        data = data_fn()
        if isinstance(data, dict) and "chart" in data:
            return data["chart"]
    except Exception:
        pass
    return None


def _inject_share_css():
    """Inject CSS for share button styling."""
    st.markdown(f"""
    <style>
    .pps-share-header {{
        font-size: 0.75rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        color: {SLATE_500};
        margin-bottom: 0.5rem;
    }}
    .pps-share-option {{
        display: flex;
        align-items: center;
        gap: 0.5rem;
        padding: 0.5rem 0.75rem;
        border-radius: 0.5rem;
        cursor: pointer;
        transition: background-color 0.15s;
        color: {SLATE_700};
        font-size: 0.9rem;
    }}
    .pps-share-option:hover {{
        background-color: {BLUE_LIGHT};
    }}
    .pps-share-divider {{
        border: none;
        border-top: 1px solid {SLATE_200};
        margin: 0.5rem 0;
    }}
    </style>
    """, unsafe_allow_html=True)


def render_share_button(page_name: str, data_fn: callable = None):
    """
    Renders a Share dropdown button using st.popover.

    Args:
        page_name: Name of the current page (for message header)
        data_fn:   Optional callable that returns dict with share data
                   {"summary": str, "table": pd.DataFrame, "chart": fig}
    """
    _inject_share_css()

    summary = _get_summary_from_data(data_fn)
    share_msg = _build_share_message(page_name, summary)

    with st.popover("\U0001f4e4 Share", use_container_width=False):

        # ── WhatsApp ──────────────────────────────────────────
        st.markdown("**\U0001f4f1 WhatsApp**")
        wa_msg = share_msg.replace("\n", "%0a")
        wa_url = f"https://wa.me/?text={wa_msg}"
        st.markdown(
            f'<a href="{wa_url}" target="_blank" '
            f'style="color:{GREEN};text-decoration:none;font-weight:600;">'
            f'Open WhatsApp &rarr;</a>',
            unsafe_allow_html=True,
        )
        with st.expander("Copy WhatsApp text", expanded=False):
            st.code(share_msg, language=None)

        st.markdown(f'<hr class="pps-share-divider">', unsafe_allow_html=True)

        # ── Telegram ─────────────────────────────────────────
        st.markdown("**\u2708\ufe0f Telegram**")
        tg_msg = share_msg.replace("\n", "%0a")
        tg_url = f"https://t.me/share/url?url=PPS+Dashboard&text={tg_msg}"
        st.markdown(
            f'<a href="{tg_url}" target="_blank" '
            f'style="color:{BLUE_PRIMARY};text-decoration:none;font-weight:600;">'
            f'Open Telegram &rarr;</a>',
            unsafe_allow_html=True,
        )
        with st.expander("Copy Telegram text", expanded=False):
            st.code(share_msg, language=None)

        st.markdown(f'<hr class="pps-share-divider">', unsafe_allow_html=True)

        # ── Email ─────────────────────────────────────────────
        st.markdown("**\u2709\ufe0f Email**")
        email_subject = st.text_input(
            "Subject",
            value=f"PPS ANANTAM \u2014 {page_name} Report",
            key=f"share_email_subject_{page_name}",
        )
        email_body = st.text_area(
            "Body",
            value=share_msg,
            height=150,
            key=f"share_email_body_{page_name}",
        )
        mailto = (
            f"mailto:?subject={email_subject.replace(' ', '%20')}"
            f"&body={email_body.replace(chr(10), '%0a').replace(' ', '%20')}"
        )
        st.markdown(
            f'<a href="{mailto}" target="_blank" '
            f'style="color:{BLUE_PRIMARY};text-decoration:none;font-weight:600;">'
            f'Open Email Client &rarr;</a>',
            unsafe_allow_html=True,
        )

        st.markdown(f'<hr class="pps-share-divider">', unsafe_allow_html=True)

        # ── PDF Export ────────────────────────────────────────
        st.markdown("**\U0001f4c4 PDF Export**")
        try:
            from components.pdf_export_engine import generate_pdf

            pdf_data = {
                "page_name": page_name,
                "summary": summary,
                "table": _get_dataframe_from_data(data_fn),
                "chart": _get_chart_from_data(data_fn),
            }
            if st.button(
                "\U0001f4c4 Generate PDF",
                key=f"share_pdf_{page_name}",
                type="secondary",
            ):
                pdf_bytes = generate_pdf(pdf_data)
                if pdf_bytes:
                    st.download_button(
                        "\u2b07\ufe0f Download PDF",
                        data=pdf_bytes,
                        file_name=f"PPS_{page_name}_{datetime.now():%Y%m%d_%H%M}.pdf",
                        mime="application/pdf",
                        key=f"share_pdf_dl_{page_name}",
                    )
                else:
                    st.warning("PDF generation returned empty data.")
        except ImportError:
            st.caption(
                "\u26a0\ufe0f PDF engine not available. "
                "Add `pdf_export_engine.py` to enable."
            )

        st.markdown(f'<hr class="pps-share-divider">', unsafe_allow_html=True)

        # ── Copy Summary ──────────────────────────────────────
        st.markdown("**\U0001f4cb Copy Summary**")
        st.code(share_msg, language=None)

        st.markdown(f'<hr class="pps-share-divider">', unsafe_allow_html=True)

        # ── Schedule Share ────────────────────────────────────
        st.markdown("**\u23f0 Schedule Share**")
        sched_col1, sched_col2 = st.columns(2)
        with sched_col1:
            sched_date = st.date_input(
                "Date",
                value=date.today(),
                key=f"share_sched_date_{page_name}",
            )
        with sched_col2:
            sched_time = st.time_input(
                "Time",
                value=dt_time(9, 0),
                key=f"share_sched_time_{page_name}",
            )

        sched_channel = st.selectbox(
            "Channel",
            options=["WhatsApp", "Telegram", "Email"],
            key=f"share_sched_channel_{page_name}",
        )

        if st.button(
            "\u23f0 Schedule",
            key=f"share_sched_btn_{page_name}",
            type="primary",
        ):
            sched_key = "pps_scheduled_shares"
            if sched_key not in st.session_state:
                st.session_state[sched_key] = []

            st.session_state[sched_key].append({
                "page_name": page_name,
                "date": str(sched_date),
                "time": str(sched_time),
                "channel": sched_channel,
                "message": share_msg,
                "created_at": datetime.now().isoformat(),
            })
            st.success(
                f"Scheduled for {sched_date.strftime('%d %b %Y')} "
                f"at {sched_time.strftime('%I:%M %p')} via {sched_channel}"
            )
